### ISSUE TITLE
Add ability to wrap advanced search blocks in groups

### ISSUE THREAD

**Issue by kamerynB** [project-lux/lux-frontend#265] opened 2024-06-07 18:36 UTC
### Note - this is pending Site Improve data.  SI data will validate whether this feature will be beneficial for other AS queries besides the one listed in BH.

**Problem Description:**
Users can't wrap existing advanced searches in groups, ie have All of, have Any of, have None of. This makes it difficult for users who want to edit existing searches. For example, a user selects "Show all x results" from an entity page and is shown a results with an advanced search, they are limited in how they can edit the advanced search.

**Expected Behavior/Solution:**
The user will be able to wrap sections in a group.

Possible options from UX/BA meeting 6/26: 
- dragging groups around to modify the AS
- adding a button above the multiple field option to make any multiple field a subquery (label: 'add single field' and image is under mockups) 
- adding a button above the first multiple field option (in comments) 
- proposed solution from IT 6/26 meeting: 
   - add an option in the multiple fields for 'add row above this' 
   - add text/button between Have Any of... and trash icon to allow for the wrapping functionality. 

**Requirements:**
TBD - Based on 6/26 meeting this will be future work as need to look at SI analytics to view if this is necessary. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [ ] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Are new regression tests required for QA - Amy
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

- https://lux-front-sbx.collections.yale.edu/view/results/objects?q=%7B%22OR%22%3A%5B%7B%22classification%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2F06cbdf76-abd6-4ea4-8385-9b42d8310e5f%22%7D%7D%2C%7B%22material%22%3A%7B%22id%22%3A%22https%3A%2F%2Flux.collections.yale.edu%2Fdata%2Fconcept%2F06cbdf76-abd6-4ea4-8385-9b42d8310e5f%22%7D%7D%5D%7D&openSearch=false

**Dependencies/Blocks:**
N/A

**Related Github Issues:**
#201 

**Related links:**

- Bugherd: https://www.bugherd.com/projects/284041/tasks/2287

**Wireframe/Mockup:**
![image](https://github.com/project-lux/lux-frontend/assets/163148482/b483716c-af95-4741-81be-d88cb271d32c)

**Comment by roamye** [comment] 2024-06-11 13:33
to do this - Is it possible to add an 'Add Row' option above any single fields (have all,any of, none)? 

such as: 
![image](https://github.com/project-lux/lux-frontend/assets/163148482/d2fe15d1-4d0a-4a01-9bdc-2cb64b4b89d5)

with the exception of having it only display 'add single field' upon its selection... Maybe it could be called **'Add Single Field' / "New Single Field"** instead? 

There may need to be an option to add this new single field onto the existing one, such that: 
have any of 
  categorized as
     id: cloth 

can become: 
have none of 
  have any of 
    categorized as
      id: cloth 

as well as become: 
have none of
   X
    have any of 
     categorized as 
       id:cloth

Let me know your thoughts @kamerynB @miketullo95

**Comment by jffcamp** [comment] 2024-06-26 21:05
Future work pending SiteImprove advanced search analytics

**Comment by jffcamp** [comment] 2024-06-26 21:08
One option - … in the have all/any of dropdown add an entry for “Add row above this”

**Comment by kamerynB** [comment] 2024-06-26 21:16
Notes from 6/25/24:

1. This may complicate advanced search further and seems like an edge case.
2. This may be adjacent to adding the ability to drag rows to different levels, which is also future work.
3. Several options were discussed. One being to have the "wrapping" button next to the row you wish to wrap. It was also discussed that the button would allow users to ONLY wrap subqueries in groups (have All of, have Any of, have None of).

**Comment by roamye** [comment] 2024-07-11 18:07
From discussion with @prowns & @miketullo95 - I created a new ticket so the information in this ticket does not get lost. Instead of adding the ability to wrap advanced search blocks what we instead want is for the opening line of an AS query (from hal link) to default to `Have All of`. 

This ticket is listed on: https://github.com/project-lux/lux-frontend/issues/290. 

Proposing to close this issue as 1) Sarah made the BH and this ticket is not what was intended from her BH comment.

**Comment by prowns** [comment] 2024-07-11 20:23
UAT - ok close, replaced by #290

**Closed** 2024-07-11 20:23 UTC
Labels: Advanced Search, Forming, future, propose-close
