### ISSUE TITLE
Search for objects with creation that was influenced by an artist  (from 2026)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#82] opened 2024-02-22 17:22 UTC
**Problem Description:**
Currently we can only search for objects created by artists  rather than ...
- creations that were influenced by an artist
- designers 
- other types of creators (unsure of what other types that would be)

**Expected Behavior/Solution:**
To be able to search for more than one creator, but not specific names. Possibly a count. 
This will be a search result type. 

**Requirements:**

- [ ] New ~accordion~ **tab** on the persons page (name: `objects influenced by this person`)  
![image](https://github.com/project-lux/lux-frontend/assets/163148482/7bbe6bf5-37f6-4dd7-adcf-4a4a95352e8d)
- [ ] It will appear as the last tab in the order. 

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

- [x] Wireframe/Mockup - Mike
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] https://github.com/project-lux/lux-marklogic/issues/51 - Peter
- [ ] Frontend requirements- TBD
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
Information of: 
- [Influenced by Joseph Wright of Derby](https://lux.collections.yale.edu/view/object/536a5eb6-bb68-439c-b199-b0e9d9f531ae)
- [Joseph Wright of Derby Search Results](https://lux.collections.yale.edu/view/results/objects/?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22joseph%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22wright%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22of%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22derby%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=joseph+wright+of+derby&is=anySortName%3Adesc&ip=2)

Should show in the new tab of  `objects influenced by this person` in persons page: 
- persons page: [Joseph Wright of Derby](https://lux.collections.yale.edu/view/person/22f9fbb3-5325-400b-a38f-ac03b4665831)

**Dependencies/Blocks:**

- Blocked By: Issues that are blocking the completion of the current issue.
- Blocking: Issues being blocked by the completion of the current issue.

**Related Github Issues:**

- Issues that contain similar work but are not blocking or being blocked by the current issue.

**Related links:**
- https://www.bugherd.com/projects/284041/tasks/1925
- [Location in lux](https://lux-front-tst.collections.yale.edu/view/results/objects?q= )
- 

**Wireframe/Mockup:**
![51](https://github.com/project-lux/lux-frontend/assets/98550395/aed7162c-e0c0-4a57-ac7b-10c959976326)

**Comment by miketullo95** [comment] 2024-03-12 19:46
@prowns question for ux/ba meeting 3/13. Made an assumption here based of ticket details. want to confirm I was heading in the right direction

**Comment by roamye** [comment] 2024-03-13 19:45
closing as this is a dupe of; https://github.com/project-lux/lux-frontend/issues/87

**Closed by roamye** 2024-03-13 19:45 UTC
Labels: Advanced Search, Forming, needs wireframe, normal
