### ISSUE TITLE
In Advanced Search, allow the creation of a new query by selecting a node within the current query to become the topmost node of the new query. (from 1735)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-frontend#30] opened 2024-02-22 17:16 UTC
https://www.bugherd.com/projects/284041/tasks/1526

**Comment by ar2674** [comment] 2024-03-04 14:56
Closing as this is a dupe of https://github.com/project-lux/lux-frontend/issues/110

**Closed by ar2674** 2024-03-04 14:56 UTC
Labels: Advanced Search, BugHerd, future, minor, POW
